# Generated by Django 5.0.6 on 2024-06-25 20:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarMake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, 
                        unique=True, 
                        help_text="Name of the car make"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description of the car make"),
                ),
                (
                    "founded",
                    models.DateField(
                        blank=True, 
                        null=True, 
                        help_text="Date the company was founded"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        max_length=100, 
                        blank=True, 
                        help_text="Country of origin"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CarModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, help_text="Name of the car model"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        max_length=50,
                        choices=[
                            ("SEDAN", "Sedan"),
                            ("SUV", "SUV"),
                            ("WAGON", "Wagon"),
                            ("COUPE", "Coupe"),
                            ("HATCHBACK", "Hatchback"),
                        ],
                        help_text="Type of the car model",
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        default=2023,
                        validators=[
                            django.core.validators.MaxValueValidator(2023),
                            django.core.validators.MinValueValidator(2015),
                        ],
                        help_text="Model year of the car",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=True, help_text="Availability of the car model"
                    ),
                ),
                (
                    "car_make",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="models",
                        to="djangoapp.carmake",
                    ),
                ),
            ],
        ),
    ]
