# Generated by Django 5.0.6 on 2024-06-28 12:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_rename_founded_carmake_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='is_available',
        ),
        migrations.AddField(
            model_name='carmodel',
            name='price',
            field=models.IntegerField(
                default=10000,
                validators=[
                    django.core.validators.MaxValueValidator(999999999),
                    django.core.validators.MinValueValidator(1),
                ],
            ),
        ),
        migrations.AlterField(
            model_name='carmake',
            name='country',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='carmake',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='carmake',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='carmake',
            name='year',
            field=models.IntegerField(
                default=2023,
                validators=[
                    django.core.validators.MaxValueValidator(2023),
                    django.core.validators.MinValueValidator(1800),
                ],
            ),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='car_make',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='models',
                to='djangoapp.carmake',
            ),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='type',
            field=models.CharField(
                choices=[
                    ('SEDAN', 'Sedan'),
                    ('SUV', 'SUV'),
                    ('WAGON', 'Wagon'),
                    ('COUPE', 'Coupe'),
                    ('HATCHBACK', 'Hatchback'),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='year',
            field=models.IntegerField(
                default=2023,
                validators=[
                    django.core.validators.MaxValueValidator(2023),
                    django.core.validators.MinValueValidator(2015),
                ],
            ),
        ),
    ]
