# Generated by Django 5.0.6 on 2024-06-28 12:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp',
         '0003_remove_carmodel_is_available_carmodel_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmake',
            name='year',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='price',
        ),
        migrations.AlterField(
            model_name='carmake',
            name='name',
            field=models.CharField(
                help_text='Name of the car make',
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='car_make',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='models',
                to='djangoapp.carmake',
            ),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='name',
            field=models.CharField(
                help_text='Name of the car model',
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='type',
            field=models.CharField(
                choices=[
                    ('SEDAN', 'Sedan'),
                    ('SUV', 'SUV'),
                    ('WAGON', 'Wagon'),
                    ('COUPE', 'Coupe'),
                    ('HATCHBACK', 'Hatchback'),
                ],
                help_text='Type of the car model',
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='year',
            field=models.IntegerField(
                default=2023,
                help_text='Model year of the car',
                validators=[
                    django.core.validators.MaxValueValidator(2023),
                    django.core.validators.MinValueValidator(2015),
                ],
            ),
        ),
    ]
